apiVersion: functions.oci.upbound.io/v1alpha1
kind: Application
metadata:
  name: application-via-crossplane
spec:
  forProvider:
    compartmentIdRef: 
      name : compartment-via-crossplane
    displayName: application-via-crossplane
    subnetIdsRefs:
      - name: subnet-via-crossplane
